### ISSUE TITLE
Getting Base-Url not working with n98-magerun2 v 2.0.0

### ISSUE THREAD

**Issue by Toffelcore** [iMi-digital/robo-run#1]
Following Function in robo-run/src/Task/MagerunTwo/ExecWithResult.php not working with n98-magerun2 version 2.0.0 when calling it by: $this->taskMagerunTwoExecWithResult()->getCurrentBaseUrl();

`/**
	 * Get the currently configured base URL
	 * @return string
	 */
	public function getCurrentBaseUrl()
	{
		$configData = $this->execAndGetJson("config:get --scope-id=0 --scope=default -- 'web/unsecure/base_url'");
		return (string) $configData->{0}->Value;
	}`

config:get has to be replaced with config:store:get

Stack Trace:
`
PHP Notice: Trying to get property of non-object in phar:///usr/local/bin/irobo/vendor/imi/robo-run/src/Task/MagerunTwo/ExecWithResult.php on line 35
PHP Stack trace:
PHP 1. {main}() /usr/local/bin/irobo:0
PHP 2. Robo\Runner->execute() /usr/local/bin/irobo:22
PHP 3. Robo\Runner->run() phar:///usr/local/bin/irobo/src/Runner.php:118
PHP 4. Robo\Application->run() phar:///usr/local/bin/irobo/src/Runner.php:165
PHP 5. Robo\Application->doRun() phar:///usr/local/bin/irobo/vendor/symfony/console/Application.php:130
PHP 6. Robo\Application->doRunCommand() phar:///usr/local/bin/irobo/vendor/symfony/console/Application.php:223
PHP 7. Consolidation\AnnotatedCommand\AnnotatedCommand->run() phar:///usr/local/bin/irobo/vendor/symfony/console/Application.php:887
PHP 8. Consolidation\AnnotatedCommand\AnnotatedCommand->execute() phar:///usr/local/bin/irobo/vendor/symfony/console/Command/Command.php:264
PHP 9. Consolidation\AnnotatedCommand\CommandProcessor->process() phar:///usr/local/bin/irobo/vendor/consolidation/annotated-command/src/AnnotatedCommand.php:394
PHP 10. Consolidation\AnnotatedCommand\CommandProcessor->validateRunAndAlter() phar:///usr/local/bin/irobo/vendor/consolidation/annotated-command/src/CommandProcessor.php:150
PHP 11. Consolidation\AnnotatedCommand\CommandProcessor->runCommandCallback() phar:///usr/local/bin/irobo/vendor/consolidation/annotated-command/src/CommandProcessor.php:181
PHP 12. call_user_func_array:{phar:///usr/local/bin/irobo/vendor/consolidation/annotated-command/src/CommandProcessor.php:235}() phar:///usr/local/bin/irobo/vendor/consolidation/annotated-command/src/CommandProcessor.php:235
PHP 13. RoboFile->dbReplace() phar:///usr/local/bin/irobo/vendor/consolidation/annotated-command/src/CommandProcessor.php:235
PHP 14. Robo\Collection\CollectionBuilder->getCurrentBaseUrl() /Users/christoph/Websites/imi/sata/RoboFile.php:173
PHP 15. Robo\Collection\CollectionBuilder->__call() /Users/christoph/Websites/imi/sata/RoboFile.php:173
PHP 16. call_user_func_array:{phar:///usr/local/bin/irobo/src/Collection/CollectionBuilder.php:399}() phar:///usr/local/bin/irobo/src/Collection/CollectionBuilder.php:399
PHP 17. iMi\RoboRun\Task\MagerunTwo\ExecWithResult->getCurrentBaseUrl() phar:///usr/local/bin/irobo/src/Collection/CollectionBuilder.php:399
`

**Comment by amenk** [comment]
Fixed in https://github.com/iMi-digital/robo-run/commit/61b004144d0103bf597d6577c136557cf2668e9c
